[package]
name = "cryptocash_starknet"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.6.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.13.0" }
cairo_verifier = { git = "https://github.com/HerodotusDev/integrity.git" }
cairo_lib = { git = "https://github.com/HerodotusDev/cairo-lib.git" }

[[target.starknet-contract]]
sierra = true

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.24.0" }

[tool.fmt]
sort-module-level-items = true